#!/usr/bin/env bash
echo "== Put objects"
set -e

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. /bucket my-bucket-name"
    exit 1
fi
if [ -z "$2" ]; then
    echo "There needs to be a filename eg. file1.txt"
    exit 1
fi
aws s3api put-object \
    --bucket $BUCKET_NAME \
    --key $OBJECT_KEY \
    --body $FILENAME